# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: e:/BaiduNetdiskDownload/E203_P3/E203_Zynq_7010/E203_Zynq_7010.srcs/sources_1/ip/clk_wiz/clk_wiz.xci
# IP: The module: 'clk_wiz' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/BaiduNetdiskDownload/E203_P3/E203_Zynq_7010/E203_Zynq_7010.srcs/sources_1/ip/clk_wiz/clk_wiz_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_wiz'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: e:/BaiduNetdiskDownload/E203_P3/E203_Zynq_7010/E203_Zynq_7010.srcs/sources_1/ip/clk_wiz/clk_wiz.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_wiz'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: e:/BaiduNetdiskDownload/E203_P3/E203_Zynq_7010/E203_Zynq_7010.srcs/sources_1/ip/clk_wiz/clk_wiz_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_wiz'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: e:/BaiduNetdiskDownload/E203_P3/E203_Zynq_7010/E203_Zynq_7010.srcs/sources_1/ip/clk_wiz/clk_wiz.xci
# IP: The module: 'clk_wiz' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/BaiduNetdiskDownload/E203_P3/E203_Zynq_7010/E203_Zynq_7010.srcs/sources_1/ip/clk_wiz/clk_wiz_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_wiz'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: e:/BaiduNetdiskDownload/E203_P3/E203_Zynq_7010/E203_Zynq_7010.srcs/sources_1/ip/clk_wiz/clk_wiz.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_wiz'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: e:/BaiduNetdiskDownload/E203_P3/E203_Zynq_7010/E203_Zynq_7010.srcs/sources_1/ip/clk_wiz/clk_wiz_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_wiz'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
